Algoritmo "NomeSalario"

Var
// Seção de Declarações das variáveis 
	nome: caracter
	salario: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

	escreval()
	escreva("Digite o nome do funcionário: ")
	leia(nome)
	escreva("Digite o salário do funcionário: ")
	leia(salario)

	escreval()
escreval("O funcionário ", nome, " tem um salário de R$", salario)

Fimalgoritmo