Algoritmo "DobroTerco"

Var
// Seção de Declarações das variáveis 
	numero, dobro, terco: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

	escreval()
	escreva("Digite um número: ")
	leia(numero)

	dobro <- numero * 2
	terco <- numero / 3

	escreval()
	escreval("Número...: ", numero)
	escreval("Dobro....: ", dobro)
	escreval("Terço....: ", terco)

Fimalgoritmo