Algoritmo "ContagemEspecificada"

Var
// Seção de Declarações das variáveis 
   i, final: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


   escreval()
   escreva("Digite um número para encerrar a contagem: ")
   leia(final)

   i <- 1
   
   enquanto i <= final faca
      escreva(i)
      i <- i + 1
   fimenquanto
   
   escreva(" Acabou!")
   escreval()
   
Fimalgoritmo