Algoritmo "DescobreNumero"

Var
// Seção de Declarações das variáveis 
   numComputador, tentativa: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval()
   
   aleatorio 1, 5
      leia(numComputador)
   aleatorio off

// limpatela

   escreva("Digite a tentativa: ")
   leia(tentativa)
   
   se tentativa = numComputador entao
      escreval("Você acertou! :D")
   senao
      escreval("Você errou! :(")
   fimse

Fimalgoritmo
