Algoritmo "SomaNumeros"

Var
// Seção de Declarações das variáveis 
   num, soma: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval()
   
   num <- 1
   soma <- 0
   
   enquanto num <> 1111 faca
      escreva("Digite um número: ")
      leia(num)
      se num <> 1111 entao
         soma <- soma + num
      fimse
   fimenquanto
   
   escreval("Soma: ", soma)

Fimalgoritmo