Algoritmo "AprendendoPortugol"

Var
// Seção de Declarações das variáveis 
   gerado: caracter
   procedimento Gerador(n: caracter)
      inicio
      escreval("+-------=======------+")
      escreval(n)
      escreval("+-------=======------+")
   fimProcedimento

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   gerado <- "  Aprendendo Portugol")
   Gerador(gerado)

Fimalgoritmo