Algoritmo "GeradorRepeticao"

Var
// Seção de Declarações das variáveis 
   i: inteiro
   procedimento Gerador(i, j: inteiro)
      inicio
         escreval("+-------=======------+")
         para i de 1 ate j faca
            escreval(" Aprendendo Portugol")
         fimpara
         escreval("+-------=======------+")
   fimProcedimento

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Gerador(5, 8)

Fimalgoritmo