Algoritmo "Soma"

Var
// Seção de Declarações das variáveis 
   num1, num2: inteiro
   procedimento Somador(n1, n2: inteiro)
      inicio
      escreval(n1, " +", n2, " =", n1 + n2)
   fimprocedimento

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   escreval()
   escreva("Digite o primero número: ")
   leia(num1)
   escreva("Digite o segundo número: ")
   leia(num2)
   
   Somador(num1, num2)

Fimalgoritmo