Algoritmo "Contador"

Var
// Seção de Declarações das variáveis 
   j, ini, fim, inc: inteiro
   procedimento Contador(i, f, c: inteiro)
      inicio
         para j de i ate f passo c faca
            escreva(j, " >>>")
         fimpara
         escreva(" FIM")
   fimProcedimento

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval()
   Contador(5, 30, 2)
   
Fimalgoritmo